version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: grooming-chimps-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=galinha
        - MYSQL_DATABASE=groomingchimps
        - MYSQL_USER=groomingchimps
        - MYSQL_PASSWORD=galinha
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: grooming-chimps-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: 
        context: ./docker/php-fpm
        dockerfile: Dockerfile
      container_name: grooming-chimps-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
